version: 0.0 # CodeDeploy Version
os: linux #
files:
  - source: / # CodeDeploy에서 전달해 준 파일 중 destination으로 이동시킬 대상, / : 모든 파일
    destination: /home/ec2-user/app/step3/zip/
    overwrite: yes

permissions: # CodeDeploy에서 EC2 서버로 넘겨준 파일들을 모두 ec2-user 권한을 가지도록 함
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks: # CodeDeploy 배포 단계에서 실행할 명령어 지정
  AfterInstall:
    - location: stop.sh
      timeout: 60 # 스크립트 실행이 60초 이상 넘어가면 실패
      runas: ec2-user # stop.sh를 ec2-user 권한으로 실행
  ApplicationStart:
    - location: start.sh
      timeout: 60
      runas: ec2-user
  ValidateService:
    - location: health.sh
      timeout: 60
      runas: ec2-user

